//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLI_HoSoBenhAnDienTu_Wed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bac_si
    {
        public bac_si()
        {
            this.dot_kham = new HashSet<dot_kham>();
            this.lich_hen = new HashSet<lich_hen>();
        }
    
        public int ma_bac_si { get; set; }
        public Nullable<long> ma_tai_khoan { get; set; }
        public Nullable<int> ma_khoa { get; set; }
        public string ho_ten { get; set; }
        public string so_chung_chi { get; set; }
        public string chuyen_khoa { get; set; }
        public string gioi_thieu { get; set; }
        public Nullable<int> kinh_nghiem { get; set; }
    
        public virtual khoa_phong khoa_phong { get; set; }
        public virtual tai_khoan tai_khoan { get; set; }
        public virtual ICollection<dot_kham> dot_kham { get; set; }
        public virtual ICollection<lich_hen> lich_hen { get; set; }
    }
}
