//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLI_HoSoBenhAnDienTu_Wed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class benh_nhan
    {
        public benh_nhan()
        {
            this.dot_kham = new HashSet<dot_kham>();
            this.lich_hen = new HashSet<lich_hen>();
        }
    
        public long ma_benh_nhan { get; set; }
        public Nullable<long> ma_tai_khoan { get; set; }
        public string so_dinh_danh { get; set; }
        public string ho_ten { get; set; }
        public System.DateTime ngay_sinh { get; set; }
        public string gioi_tinh { get; set; }
        public string dia_chi { get; set; }
        public string tien_su_benh { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
    
        public virtual tai_khoan tai_khoan { get; set; }
        public virtual ICollection<dot_kham> dot_kham { get; set; }
        public virtual ICollection<lich_hen> lich_hen { get; set; }
    }
}
