//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLI_HoSoBenhAnDienTu_Wed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_don_thuoc
    {
        public long ma_ctdt { get; set; }
        public long ma_don_thuoc { get; set; }
        public int ma_thuoc { get; set; }
        public int so_luong { get; set; }
        public string cach_dung { get; set; }
    
        public virtual don_thuoc don_thuoc { get; set; }
        public virtual thuoc thuoc { get; set; }
    }
}
