//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLI_HoSoBenhAnDienTu_Wed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_dinh_dich_vu
    {
        public long ma_chi_dinh { get; set; }
        public long ma_dot_kham { get; set; }
        public int ma_dich_vu { get; set; }
        public Nullable<int> so_luong { get; set; }
        public string ket_qua { get; set; }
        public Nullable<System.DateTime> ngay_thuc_hien { get; set; }
    
        public virtual dich_vu dich_vu { get; set; }
        public virtual dot_kham dot_kham { get; set; }
    }
}
