//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLI_HoSoBenhAnDienTu_Wed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dich_vu
    {
        public dich_vu()
        {
            this.chi_dinh_dich_vu = new HashSet<chi_dinh_dich_vu>();
        }
    
        public int ma_dich_vu { get; set; }
        public string ten_dich_vu { get; set; }
        public decimal gia_tien { get; set; }
        public string mo_ta { get; set; }
    
        public virtual ICollection<chi_dinh_dich_vu> chi_dinh_dich_vu { get; set; }
    }
}
