//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLI_HoSoBenhAnDienTu_Wed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class don_thuoc
    {
        public don_thuoc()
        {
            this.chi_tiet_don_thuoc = new HashSet<chi_tiet_don_thuoc>();
        }
    
        public long ma_don_thuoc { get; set; }
        public long ma_dot_kham { get; set; }
        public string loi_dan { get; set; }
        public Nullable<System.DateTime> ngay_ke { get; set; }
    
        public virtual ICollection<chi_tiet_don_thuoc> chi_tiet_don_thuoc { get; set; }
        public virtual dot_kham dot_kham { get; set; }
    }
}
