//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLI_HoSoBenhAnDienTu_Wed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dot_kham
    {
        public dot_kham()
        {
            this.chi_dinh_dich_vu = new HashSet<chi_dinh_dich_vu>();
            this.don_thuoc = new HashSet<don_thuoc>();
        }
    
        public long ma_dot_kham { get; set; }
        public long ma_benh_nhan { get; set; }
        public Nullable<int> ma_bac_si { get; set; }
        public Nullable<long> ma_lich_hen { get; set; }
        public Nullable<System.DateTime> thoi_gian_bat_dau { get; set; }
        public Nullable<System.DateTime> thoi_gian_ket_thuc { get; set; }
        public Nullable<int> mach { get; set; }
        public Nullable<decimal> nhiet_do { get; set; }
        public string huyet_ap { get; set; }
        public string chan_doan_so_bo { get; set; }
        public string ket_luan { get; set; }
    
        public virtual bac_si bac_si { get; set; }
        public virtual benh_nhan benh_nhan { get; set; }
        public virtual ICollection<chi_dinh_dich_vu> chi_dinh_dich_vu { get; set; }
        public virtual ICollection<don_thuoc> don_thuoc { get; set; }
        public virtual lich_hen lich_hen { get; set; }
    }
}
