//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLI_HoSoBenhAnDienTu_Wed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khoa_phong
    {
        public khoa_phong()
        {
            this.bac_si = new HashSet<bac_si>();
        }
    
        public int ma_khoa { get; set; }
        public string ten_khoa { get; set; }
        public string mo_ta { get; set; }
    
        public virtual ICollection<bac_si> bac_si { get; set; }
    }
}
