//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLI_HoSoBenhAnDienTu_Wed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lich_hen
    {
        public lich_hen()
        {
            this.dot_kham = new HashSet<dot_kham>();
        }
    
        public long ma_lich_hen { get; set; }
        public long ma_benh_nhan { get; set; }
        public Nullable<int> ma_bac_si { get; set; }
        public System.DateTime thoi_gian_hen { get; set; }
        public string trang_thai { get; set; }
        public string ly_do_kham { get; set; }
        public string ghi_chu_admin { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
    
        public virtual bac_si bac_si { get; set; }
        public virtual benh_nhan benh_nhan { get; set; }
        public virtual ICollection<dot_kham> dot_kham { get; set; }
    }
}
