//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLI_HoSoBenhAnDienTu_Wed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhan_vien
    {
        public int ma_nhan_vien { get; set; }
        public Nullable<long> ma_tai_khoan { get; set; }
        public string ho_ten { get; set; }
        public string chuc_vu { get; set; }
    
        public virtual tai_khoan tai_khoan { get; set; }
    }
}
