//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLI_HoSoBenhAnDienTu_Wed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhat_ky_he_thong
    {
        public long ma_log { get; set; }
        public string nguoi_thuc_hien { get; set; }
        public string hanh_dong { get; set; }
        public string bang_tac_dong { get; set; }
        public string du_lieu_cu { get; set; }
        public Nullable<System.DateTime> thoi_gian { get; set; }
    }
}
