//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLI_HoSoBenhAnDienTu_Wed.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class QL_BENHVIEN_WEBEntities1 : DbContext
    {
        public QL_BENHVIEN_WEBEntities1()
            : base("name=QL_BENHVIEN_WEBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bac_si> bac_si { get; set; }
        public DbSet<benh_nhan> benh_nhan { get; set; }
        public DbSet<chi_dinh_dich_vu> chi_dinh_dich_vu { get; set; }
        public DbSet<chi_tiet_don_thuoc> chi_tiet_don_thuoc { get; set; }
        public DbSet<dich_vu> dich_vu { get; set; }
        public DbSet<don_thuoc> don_thuoc { get; set; }
        public DbSet<dot_kham> dot_kham { get; set; }
        public DbSet<khoa_phong> khoa_phong { get; set; }
        public DbSet<lich_hen> lich_hen { get; set; }
        public DbSet<nhan_vien> nhan_vien { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tai_khoan> tai_khoan { get; set; }
        public DbSet<thuoc> thuoc { get; set; }
        public DbSet<vai_tro> vai_tro { get; set; }
        public DbSet<v_DanhSachChoKham> v_DanhSachChoKham { get; set; }
        public DbSet<v_HoSoBenhAnChiTiet> v_HoSoBenhAnChiTiet { get; set; }
        public DbSet<v_TopThuocBanChay> v_TopThuocBanChay { get; set; }
        public DbSet<v_BaoCaoDoanhThuThang> v_BaoCaoDoanhThuThang { get; set; }
        public DbSet<v_LichHenChoLeTan> v_LichHenChoLeTan { get; set; }
        public DbSet<nhat_ky_he_thong> nhat_ky_he_thong { get; set; }
        public DbSet<v_ThongKeBenhNhanTheoKhoa> v_ThongKeBenhNhanTheoKhoa { get; set; }
        public DbSet<v_ThongKeTyLeGioiTinh> v_ThongKeTyLeGioiTinh { get; set; }
    
        [EdmFunction("QL_BENHVIEN_WEBEntities1", "f_LayLichSuKham")]
        public virtual IQueryable<f_LayLichSuKham_Result> f_LayLichSuKham(Nullable<long> maBenhNhan)
        {
            var maBenhNhanParameter = maBenhNhan.HasValue ?
                new ObjectParameter("MaBenhNhan", maBenhNhan) :
                new ObjectParameter("MaBenhNhan", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_LayLichSuKham_Result>("[QL_BENHVIEN_WEBEntities1].[f_LayLichSuKham](@MaBenhNhan)", maBenhNhanParameter);
        }
    
        [EdmFunction("QL_BENHVIEN_WEBEntities1", "f_TimKiemBenhNhan")]
        public virtual IQueryable<f_TimKiemBenhNhan_Result> f_TimKiemBenhNhan(string tuKhoa)
        {
            var tuKhoaParameter = tuKhoa != null ?
                new ObjectParameter("TuKhoa", tuKhoa) :
                new ObjectParameter("TuKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_TimKiemBenhNhan_Result>("[QL_BENHVIEN_WEBEntities1].[f_TimKiemBenhNhan](@TuKhoa)", tuKhoaParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_BacSiKeDon(Nullable<long> maDotKham, Nullable<int> maThuoc, Nullable<int> soLuong, string cachDung)
        {
            var maDotKhamParameter = maDotKham.HasValue ?
                new ObjectParameter("MaDotKham", maDotKham) :
                new ObjectParameter("MaDotKham", typeof(long));
    
            var maThuocParameter = maThuoc.HasValue ?
                new ObjectParameter("MaThuoc", maThuoc) :
                new ObjectParameter("MaThuoc", typeof(int));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var cachDungParameter = cachDung != null ?
                new ObjectParameter("CachDung", cachDung) :
                new ObjectParameter("CachDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_BacSiKeDon", maDotKhamParameter, maThuocParameter, soLuongParameter, cachDungParameter);
        }
    
        public virtual int sp_CapNhatTrangThaiLich(Nullable<long> maLichHen, string trangThaiMoi, string ghiChu)
        {
            var maLichHenParameter = maLichHen.HasValue ?
                new ObjectParameter("MaLichHen", maLichHen) :
                new ObjectParameter("MaLichHen", typeof(long));
    
            var trangThaiMoiParameter = trangThaiMoi != null ?
                new ObjectParameter("TrangThaiMoi", trangThaiMoi) :
                new ObjectParameter("TrangThaiMoi", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatTrangThaiLich", maLichHenParameter, trangThaiMoiParameter, ghiChuParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_DangKyTaiKhoan(string username, string password, string hoTen, string sDT, Nullable<System.DateTime> ngaySinh, string gioiTinh)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DangKyTaiKhoan", usernameParameter, passwordParameter, hoTenParameter, sDTParameter, ngaySinhParameter, gioiTinhParameter);
        }
    
        public virtual int sp_DatLichKham(Nullable<long> maBenhNhan, Nullable<int> maBacSi, Nullable<System.DateTime> thoiGianHen, string lyDo)
        {
            var maBenhNhanParameter = maBenhNhan.HasValue ?
                new ObjectParameter("MaBenhNhan", maBenhNhan) :
                new ObjectParameter("MaBenhNhan", typeof(long));
    
            var maBacSiParameter = maBacSi.HasValue ?
                new ObjectParameter("MaBacSi", maBacSi) :
                new ObjectParameter("MaBacSi", typeof(int));
    
            var thoiGianHenParameter = thoiGianHen.HasValue ?
                new ObjectParameter("ThoiGianHen", thoiGianHen) :
                new ObjectParameter("ThoiGianHen", typeof(System.DateTime));
    
            var lyDoParameter = lyDo != null ?
                new ObjectParameter("LyDo", lyDo) :
                new ObjectParameter("LyDo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DatLichKham", maBenhNhanParameter, maBacSiParameter, thoiGianHenParameter, lyDoParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_Job_ArchiveBenhNhan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Job_ArchiveBenhNhan");
        }
    
        public virtual int sp_Job_BaoCaoDoanhThu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Job_BaoCaoDoanhThu");
        }
    
        public virtual int sp_Job_HuyLichQuaHan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Job_HuyLichQuaHan");
        }
    
        public virtual int sp_Job_TangGiaDichVu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Job_TangGiaDichVu");
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_TuDongSaoLuu(string loaiBackup)
        {
            var loaiBackupParameter = loaiBackup != null ?
                new ObjectParameter("LoaiBackup", loaiBackup) :
                new ObjectParameter("LoaiBackup", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TuDongSaoLuu", loaiBackupParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int sp_LeTanDuyetLich(Nullable<long> maLichHen, Nullable<int> maNhanVien, string hanhDong, Nullable<int> maBacSi)
        {
            var maLichHenParameter = maLichHen.HasValue ?
                new ObjectParameter("MaLichHen", maLichHen) :
                new ObjectParameter("MaLichHen", typeof(long));
    
            var maNhanVienParameter = maNhanVien.HasValue ?
                new ObjectParameter("MaNhanVien", maNhanVien) :
                new ObjectParameter("MaNhanVien", typeof(int));
    
            var hanhDongParameter = hanhDong != null ?
                new ObjectParameter("HanhDong", hanhDong) :
                new ObjectParameter("HanhDong", typeof(string));
    
            var maBacSiParameter = maBacSi.HasValue ?
                new ObjectParameter("MaBacSi", maBacSi) :
                new ObjectParameter("MaBacSi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LeTanDuyetLich", maLichHenParameter, maNhanVienParameter, hanhDongParameter, maBacSiParameter);
        }
    
        public virtual int sp_AdminResetMatKhau(Nullable<long> adminID, Nullable<long> targetUserID, string defaultPassword)
        {
            var adminIDParameter = adminID.HasValue ?
                new ObjectParameter("AdminID", adminID) :
                new ObjectParameter("AdminID", typeof(long));
    
            var targetUserIDParameter = targetUserID.HasValue ?
                new ObjectParameter("TargetUserID", targetUserID) :
                new ObjectParameter("TargetUserID", typeof(long));
    
            var defaultPasswordParameter = defaultPassword != null ?
                new ObjectParameter("DefaultPassword", defaultPassword) :
                new ObjectParameter("DefaultPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AdminResetMatKhau", adminIDParameter, targetUserIDParameter, defaultPasswordParameter);
        }
    
        public virtual int sp_DoiMatKhau(Nullable<long> userID, string oldPasswordHash, string newPasswordHash)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(long));
    
            var oldPasswordHashParameter = oldPasswordHash != null ?
                new ObjectParameter("OldPasswordHash", oldPasswordHash) :
                new ObjectParameter("OldPasswordHash", typeof(string));
    
            var newPasswordHashParameter = newPasswordHash != null ?
                new ObjectParameter("NewPasswordHash", newPasswordHash) :
                new ObjectParameter("NewPasswordHash", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DoiMatKhau", userIDParameter, oldPasswordHashParameter, newPasswordHashParameter);
        }
    
        public virtual int sp_TaoLichTaiKham(Nullable<long> maDotKhamCu, Nullable<int> soNgaySau, string ghiChu)
        {
            var maDotKhamCuParameter = maDotKhamCu.HasValue ?
                new ObjectParameter("MaDotKhamCu", maDotKhamCu) :
                new ObjectParameter("MaDotKhamCu", typeof(long));
    
            var soNgaySauParameter = soNgaySau.HasValue ?
                new ObjectParameter("SoNgaySau", soNgaySau) :
                new ObjectParameter("SoNgaySau", typeof(int));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaoLichTaiKham", maDotKhamCuParameter, soNgaySauParameter, ghiChuParameter);
        }
    }
}
