//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLI_HoSoBenhAnDienTu_Wed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tai_khoan
    {
        public tai_khoan()
        {
            this.bac_si = new HashSet<bac_si>();
            this.benh_nhan = new HashSet<benh_nhan>();
            this.nhan_vien = new HashSet<nhan_vien>();
        }
    
        public long ma_tai_khoan { get; set; }
        public string ten_dang_nhap { get; set; }
        public string mat_khau_hash { get; set; }
        public string email { get; set; }
        public string so_dien_thoai { get; set; }
        public string anh_dai_dien { get; set; }
        public int ma_vai_tro { get; set; }
        public Nullable<bool> dang_hoat_dong { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
        public Nullable<System.DateTime> lan_dang_nhap_cuoi { get; set; }
    
        public virtual ICollection<bac_si> bac_si { get; set; }
        public virtual ICollection<benh_nhan> benh_nhan { get; set; }
        public virtual ICollection<nhan_vien> nhan_vien { get; set; }
        public virtual vai_tro vai_tro { get; set; }
    }
}
