//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLI_HoSoBenhAnDienTu_Wed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thuoc
    {
        public thuoc()
        {
            this.chi_tiet_don_thuoc = new HashSet<chi_tiet_don_thuoc>();
        }
    
        public int ma_thuoc { get; set; }
        public string ten_thuoc { get; set; }
        public string don_vi { get; set; }
        public Nullable<decimal> don_gia { get; set; }
    
        public virtual ICollection<chi_tiet_don_thuoc> chi_tiet_don_thuoc { get; set; }
    }
}
