//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLI_HoSoBenhAnDienTu_Wed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_BaoCaoDoanhThuThang
    {
        public int Thang { get; set; }
        public int SoLuotKham { get; set; }
        public decimal TongTienDichVu { get; set; }
    }
}
