//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLI_HoSoBenhAnDienTu_Wed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_DanhSachChoKham
    {
        public long ma_lich_hen { get; set; }
        public string TenBenhNhan { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<int> Tuoi { get; set; }
        public System.DateTime thoi_gian_hen { get; set; }
        public string BacSiKham { get; set; }
        public string ten_khoa { get; set; }
    }
}
