//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLI_HoSoBenhAnDienTu_Wed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_HoSoBenhAnChiTiet
    {
        public long ma_dot_kham { get; set; }
        public string BenhNhan { get; set; }
        public string BacSi { get; set; }
        public Nullable<System.DateTime> thoi_gian_bat_dau { get; set; }
        public string chan_doan_so_bo { get; set; }
        public string ket_luan { get; set; }
        public string ThuocDaKe { get; set; }
    }
}
