//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLI_HoSoBenhAnDienTu_Wed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vai_tro
    {
        public vai_tro()
        {
            this.tai_khoan = new HashSet<tai_khoan>();
        }
    
        public int ma_vai_tro { get; set; }
        public string ten_vai_tro { get; set; }
        public string mo_ta { get; set; }
    
        public virtual ICollection<tai_khoan> tai_khoan { get; set; }
    }
}
